[connection]
url = "https://nghttp2.org/httpbin/headers"
send_goaway = false
timeout_ms = 5000

[[action]]
type = "preface"

[[action]]
type = "settings"
settings = [
  "ENABLE_PUSH=0",
  "INITIAL_WINDOW_SIZE=65535",
  "HEADER_TABLE_SIZE=8192",
]

[[action]]
type = "receive"
until = "settings"
ack_settings = true

[[action]]
type = "sleep"
duration_ms = 250

[[action]]
type = "headers"
stream_id = 1
flags = ["END_HEADERS", "END_STREAM"]
headers = [
  ":method: GET",
  ":path: /httpbin/headers",
  ":scheme: https",
  ":authority: nghttp2.org",
  "user-agent: mh2c-go-example",
]

[[action]]
type = "receive"
stream_id = 1
until = "end_stream"
ack_ping = true
